server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/product_db
    username: root
    password: Mifdha123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
#    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
